project:
  type: book

book:
  title: "Uncovering Hidden Sensitivity - Inter-Individual Growth Variation in Earthworms Under Fungicide Exposure"
  subtitle: "Git repository"
  author:
    - name: "Lisa Gollot"
      orcid: ""
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
        - name: "Experimental Toxicology and Modeling Unit, INERIS, Verneuil en Halatte 65550, France"
    - name: "Rémy Beaudouin"
      orcid: ""
      affiliations:
        - name: "Experimental Toxicology and Modeling Unit, INERIS, Verneuil en Halatte 65550, France"
    - name: "Jérôme Mathieu"
      orcid: ""
      affiliations:
        - name: "Sorbonne Université, CNRS, IRD, INRAE, Université Paris Est Créteil, Université de Paris Cité, Institute of Ecology and Environmental Sciences of Paris (iEES-Paris), Paris, France"
    - name: "Juliette Faburé"
      orcid: ""
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
    - name: "Raphaël Royauté"
      orcid: ""
      affiliations:
        - name: "Université Paris-Saclay, INRAE, AgroParisTech, UMR EcoSys, 91120 Palaiseau, France"
    
  date: "4/2/2025"
  chapters:
    - index.qmd
    - quarto/A_Context_of_the_study.qmd
    - quarto/B_Growth_experiment.qmd
    - quarto/C_Model_def_sim_data.qmd
    - quarto/D_Growth_modeling.qmd
    - quarto/E_Less_replicates.qmd
    - quarto/F_SuppInfo.qmd
    - quarto/references.qmd
  navbar:
    right:
      - icon: github
        href: https://github.com/LisaGllt/Ew-Growth-IdVar

bibliography: references/references.bib # ne pas exporter toute la bibliothèse juste la collection PhD
csl: references/apa.csl

execute:
  cache: true
  freeze: auto

format:
  html:
    code-fold: true
    code-tools: true
    code-block-bg: true
    highlight-style: appearance/lightnord.theme
    code-block-border-left: "#E5E9F0"
    code-overflow: wrap
    code-annotations: select
    theme:
      - cosmo
      - appearance/html_css.scss


editor: 
    markdown:
      canonical: true

