# How to use this repository ?

## Repository organisation

The git repository linked to this website is available [here](https://github.com/LisaGllt/Ew-Growth-IdVar) and is saved via [SoftwareHeritage](https://archive.softwareheritage.org) on this [page](https://archive.softwareheritage.org/swh:1:dir:6fcb7305c6c9cd514a610854150a8576775560dd;origin=https://github.com/LisaGllt/Ew-Growth-IdVar;visit=swh:1:snp:2c963f6a3498a98286a7cdba10a84aa7e04359aa;anchor=swh:1:rev:3ffe54fdb22d84878b17c16d0ae89657172b63d8).

Folders containing files concerning directly the study :

-   `data` folder : Contains the raw data files with direct notations from the experiments
-   `functions` folder : Contains R scripts with general functions used throughout different scripts
-   `quarto` folder : Contains all the `.qmd` files that generate the html pages, and their associated cache and files which cannot be moved to another folder.
-   `mod` folder : Contain all the models generated in `.rds` files
-   `bootstrap` folder : Contain the R script and its results concerning the bootstrap.
-   `photos` folder : Contains all photos used in html pages
-   `fig` folder : Contains all figure generated by quarto documents
-   `references` folder
    -   `apa.csl` : File of the reference style used for the website
    -   `reference.bib` : File containing all references from a zotero library

Folders concerning the setup of the git repository and the web pages :

-   `_book` : Where the final html pages are created
-   `index.qmd` : Home page of the web site (cannot be put in the `quarto` folder)
-   `_quarto.yaml` : YAML file that setup the structure of the website from the quarto (`.qmd`) documents
-   `_freeze` folder : Cache the results of code blocks (code cells) to avoid recalculating them on each execution
-   `.git`, `.gitignore` & `.github` : Git related folders
-   `.quarto` : Store configuration files, metadata, and intermediate files related to a Quarto project
-   `.Rproj.user` & `ew-growth-vi.Rproj` : R project related files
-   `html_css.scss` : CSS file to modify the look of the html pages
-   `lightnord.theme` : Theme to use for code blocks displayed in the html pages

## How to reproduce everything

If you wish to reproduce the results of this study, all you need are available in the `quarto` folder, the `mod` folder and the `bootstrap` folder.

Instructions :

-   Whether or not you want to run the models again, please delete the folders from the `quarto` folder that end by `_cache` or `_files` and delete all the figures present in the `fig` folder.
    -   If you do not want to run the models again, move on to the next step
    -   If you wish to run the models again, please delete the files in `mod/model_choice`and in `mod` (keep the arborescence)
    -   If you wish to run the bootstrap again (warning : long calculations of about 24 h on a Macbook M2), please delete the `.RData` files in the `bootstrap` folder. Run it again by just executing the `Bootstrap_VI.R` script.
-   Then, you can render again all .qmd files from the `quarto` folder in the alphabetical order of their name. Some code line will have to be de-commented for some figures to be rendered again.
